### ISSUE TITLE
No support for difficulties beyond monsoon

### ISSUE THREAD

**Issue by FORCED-REASSEMBLY** [DS-GAMING-SE/Sonic#17]
With most Mastery skins, support for difficulties beyond monsoon is needed so players can still get the mastery skin instead of having to play just monsoon. (i.e typhoon from starstorm 2)

**Comment by DxsSucuk** [comment]
Modded ones should be supported as long as their value is above monsoon?
See [this](https://github.com/DS-GAMING-SE/Sonic/blob/master/SonicTheHedgehog/Modules/Unlocks/BaseMasteryUnlockable.cs#L27) line of code and the required min value of the difficulty scale [here](https://github.com/DS-GAMING-SE/Sonic/blob/master/SonicTheHedgehog/Content/Achievements/MasteryAchievement.cs#L27)
